SELECT
  USER_ID,
  FIRST_SEEN,
  LAST_SEEN,
  CASE
    WHEN DATEDIFF(day, FIRST_SEEN, CURRENT_DATE()) <= 30 THEN 'New'
    WHEN DATEDIFF(day, LAST_SEEN, CURRENT_DATE()) <= 30
         AND DATEDIFF(day, FIRST_SEEN, LAST_SEEN) >= 365 THEN 'Loyal'
    WHEN DATEDIFF(day, LAST_SEEN, CURRENT_DATE()) > 30 THEN 'Lapsed'
  END AS USER_STATUS
FROM
  "DATA_228_PROJECT"."YELP"."USERS"